### ISSUE TITLE
[BUG] segfault from `microshift run`

### ISSUE THREAD

**Issue by jiridanek** [openshift/microshift#853]
#### What happened:

segfault

#### What you expected to happen:

🦄 

#### How to reproduce it (as minimally and precisely as possible):

Follow the steps as described in https://github.com/openshift/microshift/blob/main/docs/devenv_rhel8.md#running-microshift, except run everything directly on a Fedora machine without using any VM and use released RPM package of microshift.

After starting `microshift run` wait for it to crash after about a minute.

#### Anything else we need to know?:

I got here by trying to workaround https://github.com/openshift/microshift/issues/851

#### Environment:
- Microshift version (use `microshift version`):
```
MicroShift Version: 4.8.0-0.microshift-2022-04-20-141053
Base OKD Version: 4.8.0-0.okd-2021-10-10-030117
```
- Hardware configuration: x86_64 lenovo p1 gen2
- OS (e.g: `cat /etc/os-release`):
```
NAME="Fedora Linux"
VERSION="36 (Workstation Edition)"
ID=fedora
VERSION_ID=36
VERSION_CODENAME=""
PLATFORM_ID="platform:f36"
PRETTY_NAME="Fedora Linux 36 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:36"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f36/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=36
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=36
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```
- Kernel (e.g. `uname -a`):
```
Linux fedora.jiridanek.net 5.18.6-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jun 22 13:46:18 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
- Others:

#### Relevant Logs 

[logs.microshift.txt](https://github.com/openshift/microshift/files/9300803/logs.microshift.txt)

```
goroutine 33980 [running]:
runtime.throw({0x611e169?, 0x0?})
	/usr/lib/golang/src/runtime/panic.go:992 +0x71 fp=0xc012905af0 sp=0xc012905ac0 pc=0x1bdbad1
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:825 +0x305 fp=0xc012905b40 sp=0xc012905af0 pc=0x1bf2205
aeshashbody()
	/usr/lib/golang/src/runtime/asm_amd64.s:1343 +0x39f fp=0xc012905b48 sp=0xc012905b40 pc=0x1c0cbdf
runtime.mapiternext(0xc009ed4500)
	/usr/lib/golang/src/runtime/map.go:934 +0x2cb fp=0xc012905bb8 sp=0xc012905b48 pc=0x1bb560b
runtime.mapiterinit(0xc001434000?, 0xc01abccd00?, 0x0?)
	/usr/lib/golang/src/runtime/map.go:861 +0x228 fp=0xc012905bd8 sp=0xc012905bb8 pc=0x1bb52e8
reflect.mapiterinit(0x1bb4bfd?, 0x5a23aa0?, 0xc01abccd08?)
	/usr/lib/golang/src/runtime/map.go:1373 +0x19 fp=0xc012905c00 sp=0xc012905bd8 pc=0x1c08a19
github.com/modern-go/reflect2.(*UnsafeMapType).UnsafeIterate(...)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/github.com/modern-go/reflect2/unsafe_map.go:112
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc0110c3950, 0xc0002613f0, 0xc019095620)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/github.com/json-iterator/go/reflect_map.go:291 +0x225 fp=0xc012905d70 sp=0xc012905c00 pc=0x1ffa5e5
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc019c4ce60, 0xc0110c3680, 0xc009ed4500?)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/github.com/json-iterator/go/reflect.go:219 +0x82 fp=0xc012905da8 sp=0xc012905d70 pc=0x1ff29c2
github.com/json-iterator/go.(*Stream).WriteVal(0xc019095620, {0x5a9cb00, 0xc0110c3680})
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/github.com/json-iterator/go/reflect.go:98 +0x158 fp=0xc012905e18 sp=0xc012905da8 pc=0x1ff1cd8
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc000b80000, {0x5a9cb00, 0xc0110c3680})
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/github.com/json-iterator/go/config.go:299 +0xc9 fp=0xc012905eb0 sp=0xc012905e18 pc=0x1fe8f89
k8s.io/apiextensions-apiserver/pkg/apiserver/schema/objectmeta.GetObjectMeta(0x5a9cb00?, 0x0)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/objectmeta/coerce.go:41 +0xa2 fp=0xc012905fd0 sp=0xc012905eb0 pc=0x391b2a2
k8s.io/apiextensions-apiserver/pkg/apiserver.(*unstructuredSchemaCoercer).apply(0xc012906100, 0xc0002612b8)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go:1280 +0x125 fp=0xc012906090 sp=0xc012905fd0 pc=0x39c5045
k8s.io/apiextensions-apiserver/pkg/apiserver.schemaCoercingDecoder.Decode({{0x6c36900, 0xc0067a5310}, {0x0, 0x0, 0xc013ca8d80, {{0xc00db4e330, 0x15}, {0xc007cc3960, 0x1a}}, 0x0}}, ...)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go:1205 +0x8e fp=0xc0129060f0 sp=0xc012906090 pc=0x39c4b2e
k8s.io/apiextensions-apiserver/pkg/apiserver.(*schemaCoercingDecoder).Decode(0x60fe0e0?, {0xc010fe8580?, 0xc0002612a8?, 0xc012906210?}, 0x1bb080b?, {0x6c4b898?, 0xc0002612b8?})
	<autogenerated>:1 +0xe5 fp=0xc0129061c0 sp=0xc0129060f0 pc=0x39c6c65
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Decode(0xc019c34be0, {0xc010fe8580?, 0x45a?, 0x580?}, 0x0?, {0x6c4b898, 0xc0002612a8})
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:136 +0x1f9 fp=0xc0129062c0 sp=0xc0129061c0 pc=0x21c7a99
k8s.io/apiserver/pkg/endpoints/handlers.createHandler.func1({0x6c6bf48, 0xc000261220}, 0xc019d88f00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go:120 +0xd9b fp=0xc012906d10 sp=0xc0129062c0 pc=0x3405abb
k8s.io/apiserver/pkg/endpoints/metrics.InstrumentHandlerFunc.func1({0x7efd20496a18?, 0xc0002611c8}, 0xc019d88f00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:453 +0x2cc fp=0xc012906ea0 sp=0xc012906d10 pc=0x330858c
net/http.HandlerFunc.ServeHTTP(0x0?, {0x7efd20496a18?, 0xc0002611c8?}, 0x0?)
	/usr/lib/golang/src/net/http/server.go:2084 +0x2f fp=0xc012906ec8 sp=0xc012906ea0 pc=0x1f8882f
k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1({0x7efd20496a18?, 0xc0002611c8}, 0xc019d88f00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:59 +0x177 fp=0xc012907148 sp=0xc012906ec8 pc=0x33d4497
net/http.HandlerFunc.ServeHTTP(0x6c3f2e0?, {0x7efd20496a18?, 0xc0002611c8?}, 0xc0116908d0?)
	/usr/lib/golang/src/net/http/server.go:2084 +0x2f fp=0xc012907170 sp=0xc012907148 pc=0x1f8882f
k8s.io/apiextensions-apiserver/pkg/apiserver.(*crdHandler).ServeHTTP(0xc0019da780, {0x7efd20496a18, 0xc0002611c8}, 0xc019d88f00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go:381 +0x14a8 fp=0xc0129074c0 sp=0xc012907170 pc=0x39bbf68
k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc00a2e0f00, {0x7efd20496a18, 0xc0002611c8}, 0xc019d88f00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248 +0x658 fp=0xc012907678 sp=0xc0129074c0 pc=0x33b9d98
k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc002ffa080?, {0x7efd20496a18?, 0xc0002611c8?}, 0xc01c1ae300?)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x73 fp=0xc0129076b8 sp=0xc012907678 pc=0x33b96f3
k8s.io/apiserver/pkg/server.director.ServeHTTP({{0x6160956?, 0x330860?}, 0xc00001be60?, 0xc000130460?}, {0x7efd20496a18, 0xc0002611c8}, 0xc019d88f00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/server/handler.go:154 +0x7d1 fp=0xc012907898 sp=0xc0129076b8 pc=0x347ad51
k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc002ffa080?, {0x7efd20496a18?, 0xc0002611c8?}, 0x39?)
	<autogenerated>:1 +0x55 fp=0xc0129078e0 sp=0xc012907898 pc=0x3482c75
k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc00d796440, {0x7efd20496a18, 0xc0002611c8}, 0xc019d88f00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:254 +0x3d4 fp=0xc012907a98 sp=0xc0129078e0 pc=0x33b9b14
k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc002ffa080?, {0x7efd20496a18?, 0xc0002611c8?}, 0x0?)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x73 fp=0xc012907ad8 sp=0xc012907a98 pc=0x33b96f3
k8s.io/apiserver/pkg/server.director.ServeHTTP({{0x61398fb?, 0x1c4d4b3?}, 0xc0003aa090?, 0xc000152000?}, {0x7efd20496a18, 0xc0002611c8}, 0xc019d88f00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/server/handler.go:154 +0x7d1 fp=0xc012907cb8 sp=0xc012907ad8 pc=0x347ad51
k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0x6c710d8?, {0x7efd20496a18?, 0xc0002611c8?}, 0xc0081f7280?)
	<autogenerated>:1 +0x55 fp=0xc012907d00 sp=0xc012907cb8 pc=0x3482c75
k8s.io/kube-aggregator/pkg/apiserver.(*proxyHandler).ServeHTTP(0xc007cf5740?, {0x7efd20496a18?, 0xc0002611c8?}, 0x39?)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:122 +0x172 fp=0xc012907f38 sp=0xc012907d00 pc=0x3522f72
k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc012d4dbc0, {0x7efd20496a18, 0xc0002611c8}, 0xc019d88f00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248 +0x658 fp=0xc0129080f0 sp=0xc012907f38 pc=0x33b9d98
k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc002ffa080?, {0x7efd20496a18?, 0xc0002611c8?}, 0xc0122b1080?)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x73 fp=0xc012908130 sp=0xc0129080f0 pc=0x33b96f3
k8s.io/apiserver/pkg/server.director.ServeHTTP({{0x613d9fe?, 0x3eb509e394cb8fc7?}, 0xc006705440?, 0xc0092037a0?}, {0x7efd20496a18, 0xc0002611c8}, 0xc019d88f00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/server/handler.go:154 +0x7d1 fp=0xc012908310 sp=0xc012908130 pc=0x347ad51
k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0x6135420?, {0x7efd20496a18?, 0xc0002611c8?}, 0x9456460?)
	<autogenerated>:1 +0x55 fp=0xc012908358 sp=0xc012908310 pc=0x3482c75
k8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1.1()
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:89 +0x37 fp=0xc012908388 sp=0xc012908358 pc=0x3368977
k8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1({0x7efd20496a18, 0xc0002611c8}, 0xc019d88f00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:95 +0x1a5 fp=0xc012908448 sp=0xc012908388 pc=0x33688e5
net/http.HandlerFunc.ServeHTTP(0x6c736e8?, {0x7efd20496a18?, 0xc0002611c8?}, 0x0?)
	/usr/lib/golang/src/net/http/server.go:2084 +0x2f fp=0xc012908470 sp=0xc012908448 pc=0x1f8882f
k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1({0x7efd20496a18, 0xc0002611c8}, 0xc019d88f00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:64 +0x498 fp=0xc0129085a0 sp=0xc012908470 pc=0x3334858
net/http.HandlerFunc.ServeHTTP(0x1?, {0x7efd20496a18?, 0xc0002611c8?}, 0x7efa5e6f3ca8?)
	/usr/lib/golang/src/net/http/server.go:2084 +0x2f fp=0xc0129085c8 sp=0xc0129085a0 pc=0x1f8882f
k8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1({0x7efd20496a18, 0xc0002611c8}, 0xc019d88f00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:71 +0x178 fp=0xc012908690 sp=0xc0129085c8 pc=0x33682d8
net/http.HandlerFunc.ServeHTTP(0x614f714?, {0x7efd20496a18?, 0xc0002611c8?}, 0x9456460?)
	/usr/lib/golang/src/net/http/server.go:2084 +0x2f fp=0xc0129086b8 sp=0xc012908690 pc=0x1f8882f
k8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1.1()
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:89 +0x37 fp=0xc0129086e8 sp=0xc0129086b8 pc=0x3368977
k8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1({0x7efd20496a18, 0xc0002611c8}, 0xc019d88f00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:95 +0x1a5 fp=0xc0129087a8 sp=0xc0129086e8 pc=0x33688e5
net/http.HandlerFunc.ServeHTTP(0xc019c17080?, {0x7efd20496a18?, 0xc0002611c8?}, 0x6c0a3b0?)
	/usr/lib/golang/src/net/http/server.go:2084 +0x2f fp=0xc0129087d0 sp=0xc0129087a8 pc=0x1f8882f
k8s.io/apiserver/pkg/server/filters.WithPriorityAndFairness.func1.4()
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness.go:127 +0x16d fp=0xc012908888 sp=0xc0129087d0 pc=0x33d21ad
k8s.io/apiserver/pkg/util/flowcontrol.(*configController).Handle.func2()
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_filter.go:176 +0x1e7 fp=0xc012908970 sp=0xc012908888 pc=0x33ccc67
k8s.io/apiserver/pkg/util/flowcontrol.immediateRequest.Finish(...)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go:752
k8s.io/apiserver/pkg/util/flowcontrol.(*immediateRequest).Finish(0xc003930d36?, 0x6?)
	<autogenerated>:1 +0x2d fp=0xc012908980 sp=0xc012908970 pc=0x33ce5ad
k8s.io/apiserver/pkg/util/flowcontrol.(*configController).Handle(0xc0000d6f00, {0x6c736e8?, 0xc0110c2930}, {0xc013010160?, {0x6c74fd8?, 0xc019c17000?}}, 0xc019c4c4e0, 0x1?, 0xc0190953e0)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_filter.go:166 +0x8cb fp=0xc012908b98 sp=0xc012908980 pc=0x33cc96b
k8s.io/apiserver/pkg/server/filters.WithPriorityAndFairness.func1({0x7efd20496a18?, 0xc0002611c8}, 0xc019d88e00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness.go:130 +0x5ad fp=0xc012908d00 sp=0xc012908b98 pc=0x33d1cad
net/http.HandlerFunc.ServeHTTP(0x0?, {0x7efd20496a18?, 0xc0002611c8?}, 0x7efa5e6f3ca8?)
	/usr/lib/golang/src/net/http/server.go:2084 +0x2f fp=0xc012908d28 sp=0xc012908d00 pc=0x1f8882f
k8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1({0x7efd20496a18, 0xc0002611c8}, 0xc019d88e00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:71 +0x178 fp=0xc012908df0 sp=0xc012908d28 pc=0x33682d8
net/http.HandlerFunc.ServeHTTP(0x6135d5e?, {0x7efd20496a18?, 0xc0002611c8?}, 0x9456460?)
	/usr/lib/golang/src/net/http/server.go:2084 +0x2f fp=0xc012908e18 sp=0xc012908df0 pc=0x1f8882f
k8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1.1()
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:89 +0x37 fp=0xc012908e48 sp=0xc012908e18 pc=0x3368977
k8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1({0x7efd20496a18, 0xc0002611c8}, 0xc019d88e00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:95 +0x1a5 fp=0xc012908f08 sp=0xc012908e48 pc=0x33688e5
net/http.HandlerFunc.ServeHTTP(0xc00285a8c0?, {0x7efd20496a18?, 0xc0002611c8?}, 0x0?)
	/usr/lib/golang/src/net/http/server.go:2084 +0x2f fp=0xc012908f30 sp=0xc012908f08 pc=0x1f8882f
k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1({0x7efd20496a18, 0xc0002611c8}, 0xc019d88e00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:50 +0x214 fp=0xc012909638 sp=0xc012908f30 pc=0x33350b4
net/http.HandlerFunc.ServeHTTP(0x0?, {0x7efd20496a18?, 0xc0002611c8?}, 0x7efa5e6f3ca8?)
	/usr/lib/golang/src/net/http/server.go:2084 +0x2f fp=0xc012909660 sp=0xc012909638 pc=0x1f8882f
k8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1({0x7efd20496a18, 0xc0002611c8}, 0xc019d88e00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:71 +0x178 fp=0xc012909728 sp=0xc012909660 pc=0x33682d8
net/http.HandlerFunc.ServeHTTP(0x611dec6?, {0x7efd20496a18?, 0xc0002611c8?}, 0x9456460?)
	/usr/lib/golang/src/net/http/server.go:2084 +0x2f fp=0xc012909750 sp=0xc012909728 pc=0x1f8882f
k8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1.1()
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:89 +0x37 fp=0xc012909780 sp=0xc012909750 pc=0x3368977
k8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1({0x7efd20496a18, 0xc0002611c8}, 0xc019d88e00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:95 +0x1a5 fp=0xc012909840 sp=0xc012909780 pc=0x33688e5
net/http.HandlerFunc.ServeHTTP(0x0?, {0x7efd20496a18?, 0xc0002611c8?}, 0x7efa5e6f3ca8?)
	/usr/lib/golang/src/net/http/server.go:2084 +0x2f fp=0xc012909868 sp=0xc012909840 pc=0x1f8882f
k8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1({0x7efd20496a18, 0xc0002611c8}, 0xc019d88e00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:71 +0x178 fp=0xc012909930 sp=0xc012909868 pc=0x33682d8
net/http.HandlerFunc.ServeHTTP(0x6138eb3?, {0x7efd20496a18?, 0xc0002611c8?}, 0x9456460?)
	/usr/lib/golang/src/net/http/server.go:2084 +0x2f fp=0xc012909958 sp=0xc012909930 pc=0x1f8882f
k8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1.1()
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:89 +0x37 fp=0xc012909988 sp=0xc012909958 pc=0x3368977
k8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1({0x7efd20496a18, 0xc0002611c8}, 0xc019d88e00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:95 +0x1a5 fp=0xc012909a48 sp=0xc012909988 pc=0x33688e5
net/http.HandlerFunc.ServeHTTP(0x6c736e8?, {0x7efd20496a18?, 0xc0002611c8?}, 0x6c0a390?)
	/usr/lib/golang/src/net/http/server.go:2084 +0x2f fp=0xc012909a70 sp=0xc012909a48 pc=0x1f8882f
k8s.io/apiserver/pkg/endpoints/filters.withAuthentication.func1({0x7efd20496a18, 0xc0002611c8}, 0xc019d88e00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:80 +0x8b9 fp=0xc012909cd8 sp=0xc012909a70 pc=0x3332f99
net/http.HandlerFunc.ServeHTTP(0x6c736b0?, {0x7efd20496a18?, 0xc0002611c8?}, 0x6c0a3b0?)
	/usr/lib/golang/src/net/http/server.go:2084 +0x2f fp=0xc012909d00 sp=0xc012909cd8 pc=0x1f8882f
k8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1({0x7efd20496a18, 0xc0002611c8}, 0xc019d88b00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:80 +0x46b fp=0xc012909dc8 sp=0xc012909d00 pc=0x33685cb
net/http.HandlerFunc.ServeHTTP(0xc0183105d0?, {0x7efd20496a18?, 0xc0002611c8?}, 0xc010be9140?)
	/usr/lib/golang/src/net/http/server.go:2084 +0x2f fp=0xc012909df0 sp=0xc012909dc8 pc=0x1f8882f
k8s.io/apiserver/pkg/server/filters.WithCORS.func1({0x7efd20496a18, 0xc0002611c8}, 0xc019d88b00)
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/server/filters/cors.go:75 +0x10b fp=0xc012909f50 sp=0xc012909df0 pc=0x33ceeab
net/http.HandlerFunc.ServeHTTP(0x2118800?, {0x7efd20496a18?, 0xc0002611c8?}, 0xc0069c1e00?)
	/usr/lib/golang/src/net/http/server.go:2084 +0x2f fp=0xc012909f78 sp=0xc012909f50 pc=0x1f8882f
k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1()
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:107 +0xa2 fp=0xc012909fe0 sp=0xc012909f78 pc=0x33d3262
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc012909fe8 sp=0xc012909fe0 pc=0x1c0f7e1
created by k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	/builddir/build/BUILD/microshift-48863ff4cf9146906a7d7879c2ca93265c7ad662/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:93 +0x2cc
```

**Comment by dhellmann** [comment]
We're focusing on RHEL support for the moment and the main branch has moved on quite a bit from the 4.8 release branch. You could try compiling the main branch, but it may be a few months before the team returns to focusing on Fedora support.

**Comment by jiridanek** [comment]
main segfaulted for me as well
